### ISSUE TITLE
WaitUntil 사용 할 수 없나요?

### ISSUE THREAD

**Issue by huri92** [naverz/zepeto-script-sample#67]
```typescript

        yield new WaitUntil(()=>this.CountDown());

```

```typescript
private CountDown():bool
    {
        if(this.m_CountDown == 0)
            return true;
        else
            return false;
    }
```

return을 boolean 으로 해도 bool로 해도 같습니다.
아래는 오류 목록입니다.
Exception: file://C:\GitLab\ZEPETO\TesterHoon\Assets\Scripts\CheeseGame.js:16: Error: c# exception:can not find delegate bridge for System.Func<bool>,stack:  at Puerts.GeneralGetterManager+<>c__DisplayClass26_0.<MakeTranslateFunc>b__1 (System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x0004b] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.Parameters.GetArguments (Puerts.CallInfo callInfo) [0x000e1] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.OverloadReflectionWrap.Construct (Puerts.CallInfo callInfo) [0x00028] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.MethodReflectionWrap.Construct (System.IntPtr isolate, System.IntPtr info, System.Int32 argumentsLen) [0x00029] in <5c8d3b87a56347e0b5943ffe2015e513>:0 GS�u�=���<

Error: c# exception:can not find delegate bridge for System.Func<bool>,stack:  at Puerts.GeneralGetterManager+<>c__DisplayClass26_0.<MakeTranslateFunc>b__1 (System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x0004b] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.Parameters.GetArguments (Puerts.CallInfo callInfo) [0x000e1] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.OverloadReflectionWrap.Construct (Puerts.CallInfo callInfo) [0x00028] in <5c8d3b87a56347e0b5943ffe2015e513>:0 
  at Puerts.MethodReflectionWrap.Construct (System.IntPtr isolate, System.IntPtr info, System.Int32 argumentsLen) [0x00029] in <5c8d3b87a56347e0b5943ffe2015e513>:0 GS�u�=���<
    at CheeseGame.DoDoutine (file://C:\GitLab\ZEPETO\TesterHoon\Assets\Scripts\CheeseGame.js:16:15)
    at DoDoutine.next (<anonymous>)
    at file://C:\GitLab\ZEPETO\TesterHoon\builtin\proxy.js:24:45
Puerts.GenericDelegate.Func[TResult] () (at <5c8d3b87a56347e0b5943ffe2015e513>:0)
ZEPETO.Script.ZepetoScriptBehaviour+<OnStartCoroutine>d__98.MoveNext () (at <5c8d3b87a56347e0b5943ffe2015e513>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ef667cdc82bf4a4e911d1ddea9ff581d>:0)

**Comment by crash-kim** [comment]
안녕하세요.
WaitUntil, WaitWhile은 현재 이슈가 있어 동작하지 않습니다.
다음 버전에 수정해서 나갈 예정입니다. (zepeto.world@1.0.5)

**Comment by JeongDongBaek** [comment]
아직 안되나요?
